language: node_js
node_js: node
cache: npm
script:
  - echo "No tests to run..."
before_deploy:
  - npm install -g firebase-tools
deploy:
  - provider: script
    skip_cleanup: true
    script: $(npm bin -g)/firebase deploy --project reach-ui --message "https://travis-ci.com/$TRAVIS_REPO_SLUG/builds/$TRAVIS_BUILD_ID"
      --token $FIREBASE_TOKEN --non-interactive --force
    on:
      branch: master
